[__config__]
newver = "new_ver.json"

[typora]
source = "cmd"
cmd = '''
curl -s https://www.typora.io/linux/Packages | grep Version | cut -f 2 -d ' ' | sort -V | cut -f 1 -d '-' | uniq | tail -n 1
'''
