[__config__]
newver = "new_ver.json"
oldver = "old_ver.json"

[cachyos-keyring]
source = "cmd"
cmd = '''
curl -s https://raw.githubusercontent.com/CachyOS/CachyOS-PKGBUILDS/refs/heads/master/cachyos-keyring/PKGBUILD | grep '^pkgver=' | awk -F '=' '{print $2}'
'''

[dae]
source = "github"
github = "daeuniverse/dae"
use_latest_release = true

[LiteLoaderQQNT]
source = "github"
github = "LiteLoaderQQNT/LiteLoaderQQNT"
use_latest_release = true

[LiteLoaderQQNT-lite_tools]
source = "github"
github = "xiyuesaves/LiteLoaderQQNT-lite_tools"
use_latest_release = true

[LiteLoaderQQNT-Pangu]
source = "github"
github = "MisaLiu/LiteLoaderQQNT-Pangu"
use_latest_release = true

[LiteLoaderQQNT-pURLfy]
source = "github"
github = "PRO-2684/LiteLoaderQQNT-pURLfy"
use_latest_release = true

[transitio]
source = "github"
github = "PRO-2684/transitio"
use_latest_release = true

[maple-font]
source = "github"
github = "subframe7536/maple-font"
use_latest_release = true

[minegrub-theme]
source = "github"
github = "Lxtharia/minegrub-theme"
use_latest_release = true

[typora]
source = "cmd"
cmd = '''
curl -s https://www.typora.io/linux/Packages | grep Version | cut -f 2 -d ' ' | sort -V | cut -f 1 -d '-' | uniq | tail -n 1
'''

[v2ray-rules-dat]
source = "github"
github = "Loyalsoldier/v2ray-rules-dat"
use_latest_tag = true

[v2rayn]
source = "github"
github = "2dust/v2rayN"
include_prereleases = true
use_max_tag = true

[xray]
source = "github"
github = "XTLS/Xray-core"
include_prereleases = true
use_max_tag = true

[qbittorrent-enhanced]
source = "github"
github = "c0re100/qBittorrent-Enhanced-Edition"
use_latest_tag = true
prefix = "release-"

[klassy]
source = "github"
github = "paulmcauley/klassy"
use_latest_tag = true

[sing-box]
source = "github"
github = "SagerNet/sing-box"
use_latest_release = true

[openlist]
source = "github"
github = "OpenListTeam/OpenList"
use_latest_release = true
