[__config__]
newver = "new_ver.json"
oldver = "old_ver.json"

[typora]
source = "cmd"
cmd = '''
curl -s https://www.typora.io/linux/Packages | grep Version | cut -f 2 -d ' ' | sort -V | cut -f 1 -d '-' | uniq | tail -n 1
'''

[64gram-desktop]
source = "github"
github = "TDesktop-x64/tdesktop"
use_latest_release = true

[dae]
source = "github"
github = "daeuniverse/dae"
use_latest_release = true

[xray]
source = "github"
github = "XTLS/Xray-core"
include_prereleases = true
use_max_tag = true

[cachyos-keyring]
source = "cmd"
cmd = '''
curl -s https://raw.githubusercontent.com/CachyOS/CachyOS-PKGBUILDS/refs/heads/master/cachyos-keyring/PKGBUILD | grep '^pkgver=' | awk -F '=' '{print $2}'
'''
