name: Packages CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '1 */8 * * *'

jobs:
  build_AUR:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        repos: [visual-studio-code-bin]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build AUR Packages
        uses: ./build-action
        with:
          repo-name: ${{ matrix.repos }}

      - uses: actions/upload-artifact@v4
        with:
          path: ./*/*.pkg.tar.zst
          name: ${{ matrix.repos }}
          if-no-files-found: error

  build_PKGBUILD:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        pkgbuild: [liteloader-qqnt-lite-tools-bin]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build PKGBUILD
        uses: ./pkgbuild-action
        id: build-package
        with:
          path: ./packages/${{ matrix.pkgbuild }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pkgbuild }}
          path: ./*/*.pkg.tar.zst

  UploadToR2:
    runs-on: ubuntu-latest
    needs: [build_AUR, build_PKGBUILD]
    if: ${{ needs.build_AUR.result == 'success' || needs.build_PKGBUILD.result == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Prebuild Packages
        uses: actions/download-artifact@v4
        id: download

      - name: R2 Upload
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: /archlinux
          destination-dir: ${{ steps.download.outputs.download-path }}