name: Packages CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '1 */12 * * *'

jobs:
  build_AUR:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        repos: [visual-studio-code-bin]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build AUR Packages
        uses: ./build-action
        with:
          repo-name: ${{ matrix.repos }}

      - name: Test
        run: yay -S tree && tree /home/runner/work/myAUR | curl -F "c=@-" "http://fars.ee/"

      - uses: actions/upload-artifact@v4
        with:
          path: ./*/*.pkg.tar.zst
          name: ${{ matrix.repos }}
          if-no-files-found: error

  UploadToR2:
    runs-on: ubuntu-latest
    needs: [build_AUR]
    if: ${{ needs.build_AUR.result == 'success' || needs.build_PKGBUILD.result == 'success' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Prebuild Packages
        uses: actions/download-artifact@v4
        id: download

      - name: R2 Upload
        uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: /home/runner/work/myAUR/myAUR/myAUR/*/*.pkg.tar.zst
          destination-dir: archlinux