name: Packages CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./build-action
        with:
          pkgdir: ./packages