name: Build Packages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4

      - name: PKGBUILD Action
        uses: ouuan/pkgbuild-action@v1.2.0
        with:
          path: .

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: pkgname-${{ github.run_id }}
          path: ${{ steps.build-package.outputs.pkgfile }}
