name: Build Packages Cache

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "yay-bin/PKGBU1LD"
      - "linuxqq/PKGBU1LD"
      - ".github/workflows/build-packages-cache.yml"

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - name: 仓库导入 PKGBUILD
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: 生成数组
        id: generate-matrix
        run: |
          sudo apt-get install jq
          MATRIX_JSON=`find * -type f -name "PKGBU1LD" -printf "%h\n" | jq -Rnc '."package" |= [inputs]'`
          echo ${MATRIX_JSON}
          echo "matrix=${MATRIX_JSON}" >> $GITHUB_OUTPUT

  build:
    needs: metadata
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    continue-on-error: true
    strategy:
      max-parallel: 5
      matrix: ${{ fromJson(needs.metadata.outputs.matrix) }}
      fail-fast: false
    steps:
      - name: 安装依赖
        run: |
          echo "REPO_FOLDER=$GITHUB_WORKSPACE/repo/x86_64" >> $GITHUB_ENV
          pacman -Syyu --noconfirm --needed --ignore filesystem git pacman-contrib

      - name: 仓库导入 PKGBUILD
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: 配置环境
        run: |
          sed -i 's#\(^OPTIONS.*\)\(debug\)\(.*\)#\1!\2\3#' /etc/makepkg.conf
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder
          mkdir -p ${REPO_FOLDER}
          chown -R builder:builder ./

      - name: 构建 yay
        working-directory: ./yay-bin
        run: |
          sudo -u builder PKGDEST=${REPO_FOLDER} makepkg -si --noconfirm --needed -p PKGBU1LD
          sudo -u builder yay --version

      - name: 构建 ${{ matrix.package }}
        working-directory: ./${{ matrix.package }}
        run: |
          # 安装相关包依赖
          sudo -u builder yay -Sy --noconfirm \
            $(pacman --deptest \
              $(source ./PKGBU1LD &&\
              echo ${depends[@]} ${checkdepends[@]} ${makedepends[@]}))
          
          # 验证文件完整性
          sudo -u builder updpkgsums PKGBU1LD

          # 开始构建
          sudo -u builder PKGDEST=${REPO_FOLDER} makepkg -si --noconfirm --needed -p PKGBU1LD

      - name: 保存包缓存 # 后续只需要在 path 中添加包文件路径
        uses: actions/cache/save@v4
        with:
          path: |
            /var/lib/pacman/local
            /usr/bin/yay
            /opt/QQ
            /usr/bin/linuxqq
          key: packages-cache
