name: Build paru Cache

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/build-paru-cache.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - name: 安装依赖
        run: pacman -Syyu --noconfirm --needed --ignore filesystem git

      - name: 配置环境
        run: |
          sed -i 's#\(^OPTIONS.*\)\(debug\)\(.*\)#\1!\2\3#' /etc/makepkg.conf
          useradd -m builder
          echo "builder ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/builder

      - name: 构建 paru
        working-directory: /tmp
        run: |
          sudo -u builder git clone https://aur.archlinux.org/paru.git
          cd paru
          sudo -u builder makepkg -si --noconfirm --needed
          sudo -u builder paru --version

      - name: 保存 paru 缓存
        uses: actions/cache/save@v4
        with:
          path: /usr/bin/paru
          key: paru-cache
