name: Run nvchecker

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - nvcheck
    paths:
      - "config.toml"
      - ".github/workflows/nvchecker.yml"

jobs:
  check-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 安装 nvchecker
        run: |
          python -m pip install --upgrade nvchecker

      - name: 导入仓库
        uses: actions/checkout@v4

      - name: 运行 nvchecker
        run: |
          nvchecker --file .github/config.toml
      
      - name: 保存版本文件
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[杂项]: 更新依赖版本"
          branch: nvcheck
          commit_options: "--no-verify --signoff"
          file_pattern: 'new_ver.json'

          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
