name: Check and Update

on:
  workflow_dispatch:
  schedule:
    - cron: "2 */2 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/nvchecker.toml"
      - ".github/renovate.json"
      - ".github/workflows/run-nvchecker-and-renovate.yml"

jobs:
  check-versions:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    permissions:
      contents: write
    steps:
      - name: 安装依赖
        run: pacman -Syyuu --noconfirm --needed --ignore filesystem nvchecker git jq

      - name: 导入仓库
        uses: actions/checkout@v4

      - name: 配置环境
        run: sed -i -e "s/__GITHUB_ACCESS_TOKEN__/${{ secrets.GITHUB_TOKEN }}/g" ./.github/keyfile.toml

      - name: 运行 Nvchecker
        working-directory: ./.github
        run: |
          # keyfile 用于提升 GitHub API 请求限额
          nvchecker --file nvchecker.toml --keyfile keyfile.toml
          # 精简输出内容
          jq '.data |= with_entries(.value |= {version: .version})' new_ver.json > temp.json
          mv temp.json new_ver.json
          nvcmp --file nvchecker.toml > result.tmp
          nvtake --file nvchecker.toml --all

      - name: 信任仓库
        run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}

      - name: 保存版本文件
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[CI]: 更新版本记录"
          branch: main
          commit_options: "--no-verify --signoff"
          file_pattern: './.github/new_ver.json ./.github/old_ver.json'
          commit_user_name: YanamiChan[bot]
          commit_user_email: 182213109+YanamiChan[bot]@users.noreply.github.com
          commit_author: YanamiChan[bot] <182213109+YanamiChan[bot]@users.noreply.github.com>

      - name: 推送更新通知
        run: |
          RESULT=$(cat ./.github/result.tmp) \
          && [ ! -z $RESULT ] \
          && curl "https://${{ secrets.SERVERCHAN_UID }}.push.ft07.com/send/${{ secrets.SERVERCHAN_SENDKEY }}.send" \
            --data-urlencode "title=软件包更新" \
            --data-urlencode "desp=$RESULT" \
          || echo "No new versions" \

  update-versions:
    needs: check-versions
    runs-on: ubuntu-latest
    steps:
      - name: 生成 Token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: 导入仓库
        uses: actions/checkout@v4

      - name: 运行 Renovate
        uses: renovatebot/github-action@v41.0.3
        with:
          configurationFile: .github/renovate.json
          token: "${{ steps.generate-token.outputs.token }}"