name: Check and Update

on:
  workflow_dispatch:
  schedule:
    - cron: "2 */2 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/nvchecker.toml"
      - ".github/renovate.json"
      - ".github/workflows/run-nvchecker-and-renovate.yml"

jobs:
  check-versions:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    permissions:
      contents: write
    outputs:
      version-file: ${{ steps.version-file.outputs.version-file }}
    steps:
      - name: 安装依赖
        run: pacman -Syyuu --noconfirm --needed --ignore filesystem nvchecker git

      - name: 导入仓库
        uses: actions/checkout@v4

      - name: 运行 Nvchecker
        id: version-file
        working-directory: ./.github
        run: |
          nvchecker --file nvchecker.toml >> "$GITHUB_OUTPUT"
          echo "$GITHUB_OUTPUT"

  update-versions:
    needs: check-versions
    runs-on: ubuntu-latest
    steps:
      - name: 生成 Token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: 导入仓库
        uses: actions/checkout@v4

      - name: 写入 new_ver.json
        run: |
          echo '${{ fromJson(needs.check-versions.outputs.version-file) }}' > new_ver.json
          echo '${{ fromJson(needs.check-versions.outputs.version-file) }}'

      - name: 运行 Renovate
        uses: renovatebot/github-action@v40.2.10
        with:
          configurationFile: .github/renovate.json
          token: "${{ steps.generate-token.outputs.token }}"