name: Check and Update

on:
  workflow_dispatch:
  schedule:
    - cron: "2 */2 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/nvchecker.toml"
      - ".github/renovate.json"
      - ".github/workflows/run-nvchecker-and-renovate.yml"

jobs:
  check-versions:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    permissions:
      contents: write
    steps:
      - name: 安装依赖
        run: pacman -Syyuu --noconfirm --needed --ignore filesystem nvchecker git

      - name: 导入仓库
        uses: actions/checkout@v4

      - name: 运行 nvchecker
        working-directory: ./.github
        run: nvchecker --file nvchecker.toml
      
      - name: 解决 git safe.directory 问题
        run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}

      - name: 保存版本文件
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[nvchecker]: 更新依赖版本"
          branch: main
          commit_options: "--no-verify --signoff"
          file_pattern: './.github/new_ver.json'
          commit_user_name: YanamiChan[bot]
          commit_user_email: 182213109+yanamichan[bot]@users.noreply.github.com
          commit_author: YanamiChan[bot] <182213109+yanamichan[bot]@users.noreply.github.com>

  update-versions:
    needs: check-versions
    runs-on: ubuntu-latest
    steps:
      - name: 生成 Token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: 导入仓库
        uses: actions/checkout@v4

      - name: 运行 renovate
        uses: renovatebot/github-action@v40.2.10
        with:
          configurationFile: .github/renovate.json
          token: "${{ steps.generate-token.outputs.token }}"